name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}"
  OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}"
  CLERK_SECRET_KEY="${{ secrets.CLERK_SECRET_KEY }}"
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}}"
  DATABASE_URL="${{ secrets.DATABASE_URL }}"
  UPSTASH_REDIS_REST_URL="${{ secrets.UPSTASH_REDIS_REST_URL }}"
  UPSTASH_REDIS_REST_TOKEN="${{ secrets.UPSTASH_REDIS_REST_TOKEN }}"
  QSTASH_URL="${{ secrets.QSTASH_URL }}"
  QSTASH_TOKEN="${{ secrets.QSTASH_TOKEN }}"
  QSTASH_NEXT_SIGNING_KEY="${{ secrets.QSTASH_NEXT_SIGNING_KEY }}"
  QSTASH_CURRENT_SIGNING_KEY="${{ secrets.QSTASH_CURRENT_SIGNING_KEY }}"
  MY_AWS_ACCESS_KEY_ID="${{ secrets.MY_AWS_ACCESS_KEY_ID }}"
  MY_AWS_BUCKET_NAME="${{ secrets.MY_AWS_BUCKET_NAME }}"
  MY_AWS_SECRET_KEY="${{ secrets.MY_AWS_SECRET_KEY }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"

      # Install SST
      - run: npm i -g sst

      # Install packages
      - run: yarn install --frozen-lockfile

      # Build app
      - run: yarn build
